config/routes.rb
Rails.application.routes.draw do

  # get 'hello_world', to: 'hello_world#index'
  root 'events#index'

  resources :events

  resources :projects do
    resources :todos
  end

  resources :teams do
    resources :projects
  end


  devise_for :users
end

app/models/access.rb
class Access < ApplicationRecord
  belongs_to :project
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :title
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :from, class_name: "User", foreign_key: "from_id"
  belongs_to :todo
  belongs_to :team
  belongs_to :project

  paginates_per 50

  def action
    %w(创建了任务 删除了任务 完成了任务 分派了任务 重新分派了任务 修改了任务到期 评论了任务).at(actions)
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :team

  has_many :todos
  has_many :events
  has_and_belongs_to_many :users, join_table: :users_projects
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :projects
  has_many :users
  has_many :events
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :project

  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :team

  has_many :events, foreign_key: :from_id
  has_and_belongs_to_many :projects, join_table: :users_projects

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :team_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    if params[:projects].present?
      unless params[:projects].include? "0"
        events = current_user.team
                             .events
                             .where(project_id: params[:projects])
                             .page(params[:page])
      end
    else
      events = current_user.team.events.page(params[:page])
    end

    if events.nil?
      @events = []
    else
      events_days = events.select('Date(created_at)')
                          .distinct
                          .pluck('Date(created_at)')

      @events = events_days.sort.reverse.map do |date|
                   events.where('Date(created_at) == ?', date)
                         .order(created_at: 'DESC')
                         .as_json(methods: :action,
                           include: {from: {only: [:id, :name]},
                                     todo: {include: {project:
                                              {include: :team}}}})
               end

    end

    @projects = [{ id: 0, name: '所有项目和日历' }]
    @projects << current_user.team.projects.select(:id, :name).as_json
    @projects.flatten!

    @members = [{ id: 0, name: '所有成员' }]
    @members << current_user.team.users.select(:id, :name).as_json
    @members.flatten!

  end
end

app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projecs = Team.find(params[:team_id]).projects
  end

  def new
    @project = Team.find(params[:team_id]).projects.build
  end

  def create
    @project = Team.find(params[:team_id]).projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to team_project_url(params[:team_id], @project.id), notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  private

    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_team
      @team = Team.find params[:id]
    end

    def team_params
      params.require(:team).permit(:name)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Project.find(params[:project_id]).todos
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Project.find(params[:project_id]).todos.build
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :content, :due_date, :executor_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/events/_filters.html.erb
<div class="filters">
  <span class="filters-title">筛选动态</span>
  <div class="filter filter-project">
    <div class="simple-select require-select selected">
      <input type="text" class="select-result" autocomplete="off" placeholder="">
      <span class="link-expand" title="所有选项">
        <i class="icon-caret-down">
          <span>▾</span></i>
      </span>
      <span class="link-clear" title="清除选择">
        <i class="icon-delete">
        <span>✕</span></i>
      </span>
      <div class="select-list" style="display: none;">
        <div class="select-item all-item selected">
          <a href="javascript:;" class="label">
            <span>所有项目、日历和周报</span>
          </a>
        </div>
        <div class="select-item">
          <a href="javascript:;" class="label">
            <span>熟悉Tower</span>
          </a>
        </div>
        <div class="select-item">
          <a href="javascript:;" class="label">
            <span>老麻来啦</span>
          </a>
        </div>
      </div>
    </div>
    <select id="project-filter-select" style="display: none;">
      <option value="-1" selected="">所有项目、日历和周报</option>
      <option value="715c1e2bf8c045b5879eec6f492bcbde" data-key="shuxitower sxTower 熟悉Tower">
         熟悉Tower
      </option>
      <option value="48dbafd63883428c98f05544a3608f2f" data-key="laomalaila lmll 老麻来啦">
        老麻来啦
      </option>
    </select>
  </div>

  <div class="filter filter-member">
    <div class="simple-select member-filter require-select selected">
      <input type="text" class="select-result" autocomplete="off" placeholder="">
      <span class="link-expand" title="所有选项">
      <i class="icon-caret-down">
        <span>▾</span>
      </i>
      </span>
      <span class="link-clear" title="清除选择">
        <i class="icon-delete">
          <span>✕</span>
        </i>
      </span>
      <div class="select-list" style="display: none;">
        <div class="select-item all-item selected">
          <a href="javascript:;" class="label">
            <span>所有成员</span>
          </a>
        </div>
        <div class="select-item member-item">
          <img src="/assets/default_avatars/noon.jpg" class="avatar">
          <a href="javascript:;" class="label member-item">
            <span>淇淇</span>
          </a>
        </div>
        <div class="select-item member-item">
          <img src="/assets/default_avatars/nightfall.jpg" class="avatar">
            <a href="javascript:;" class="label member-item">
              <span>王强生</span>
            </a>
        </div>
      </div>
    </div>
    <select id="member-filter-select" style="display: none;">
      <option value="-1" selected="">所有成员</option>
      <option value="4a" data-gavatar="/assets/default_avatars/noon.jpg" data-key="qiqi qq 淇淇">
        淇淇
      </option>
      <option value="593c1a0d300a40ae9b9d5890f9c0930b" data-gavatar="/assets/default_avatars/nightfall.jpg" data-key="wangqiangsheng wqs 王强生">
        王强生
      </option>
   </select>
  </div>
</div>

app/views/events/_footer.html.erb
<div class="footer">
© <a href="http://mycolorway.com" target="_blank">彩程设计</a>
</div>

app/views/events/_header.html.erb
<div class="header">
  <h1 class="logo">
      <a href="javascript:;" class="link-team-menu">
          <span class="name">laomalaila</span>
          <i class="twr twr-caret-down"></i>
      </a>
  </h1>

  <ul class="nav">
      <li class="" id="nav-project">
          <a href="/teams/1e4c353f36b54569ab7d1f3eec2d9776/projects" data-stack="" data-stack-root="">项目</a>
      </li>
      <li class="active" id="nav-events">
          <a href="/teams/1e4c353f36b54569ab7d1f3eec2d9776/events" data-stack="" data-stack-root="">动态</a>
      </li>
      <li class="" id="nav-calendar">
          <a href="/teams/1e4c353f36b54569ab7d1f3eec2d9776/calendars" data-stack="" data-stack-fluid="" data-stack-root="">日历</a>
      </li>

          <li class="" id="nav-week">
              <a href="/teams/1e4c353f36b54569ab7d1f3eec2d9776/weekly_reports" data-stack="" data-stack-root="">周报</a>
          </li>

      <li class="" id="nav-members">
          <a href="/teams/1e4c353f36b54569ab7d1f3eec2d9776/members" data-stack="" data-stack-root="">团队</a>
      </li>
      <li class="" id="nav-me">
          <a href="/members/593c1a0d300a40ae9b9d5890f9c0930b?me=1" data-stack="" data-stack-root="">我自己</a>
      </li>
  </ul>

  <div class="command-bar">
      <div class="search-wrap">
          <a href="javascript:;" class="link-search" title="搜索"><i class="twr twr-search"></i></a>
          <form id="form-search" class="form" method="get" action="/teams/1e4c353f36b54569ab7d1f3eec2d9776/search">
              <input id="txt-search" type="text" class="keyword no-border" name="keyword" placeholder="搜索" autocomplete="off">
          </form>
      </div>
      <div class="notification-info">
          <a href="javascript:;" id="notification-count" class="label " title="新的通知" data-unread-count="0" data-url="/teams/1e4c353f36b54569ab7d1f3eec2d9776/notifications/unread_counts">
              <span class="twr twr-bell-o bell"></span>
              <span class="num">0</span>
          </a>
          <div class="noti-pop">
              <div class="noti-pop-hd">
                  <span class="title">通知</span>
                  <a class="noti-settings" href="/members/593c1a0d300a40ae9b9d5890f9c0930b/notification_settings/" title="设置通知发送方式" data-stack="" data-stack-root="">
                      <i class="twr twr-cog"></i>
                  </a>
                  <a id="noti-mark-read" class="mark-as-read" href="javascript:;" title="全部标记为已读">
                      <i class="twr twr-check"></i>
                  </a>
              </div>
              <div class="noti-pop-list notification-list">
              </div>
              <div class="noti-pop-empty">- 没有新通知 -</div>
              <div class="noti-pop-action">
                  <a class="noti-all-link" href="/teams/1e4c353f36b54569ab7d1f3eec2d9776/notifications/" data-stack="" data-stack-root="">查看全部</a>
              </div>
          </div>
      </div>
      <div class="account-info">
          <div class="member-settings">
              <a class="link-member-menu" href="javascript:;" title="王强生">
                  <img class="avatar" src="/assets/default_avatars/nightfall.jpg" alt="王强生">
                  <span class="twr twr-caret-down"></span>
              </a>
          </div>
      </div>
  </div>
</div>

app/views/events/_team_events.html.erb
<div class="team-events">
  <div class="events-day" data-absdate="2016-11-02T00:00:00+08:00">
    <h4 class="events-day-title">昨</h4>
    <div class="events-day-content">
      <div class="events-ancestor" data-ancestor-guid="64fc76d9796d4f86920fdfe0660cd3cc">
        <h5 class="events-ancestor-title">
          <a href="/teams/124c/calendars" target="_blank" title="工作安排">工作安排</a>
        </h5>
        <div class="event event-common event-calendarevent-add" id="event-87764719" data-ancestor-guid="64fc76d9796d4f86920fdfe0660cd3cc" data-ancestor-name="工作安排" data-ancestor-url="/teams/124c/calendars">
          <a href="/members/4a" class="from" target="_blank">
            <img alt="淇淇" class="avatar" src="https://tower.im/assets/default_avatars/noon.jpg"></a>
            <i class="icon-event"></i>
            <div class="event-main">
              <div class="event-head">
                <a href="#event-87764719" data-created-at="2016-11-02T22:09:27+08:00" class="event-created-at">22:09</a>
                <span class="event-actor">
                  <a href="/members/4a" class="link-member" target="_blank">淇淇</a>
                </span>
                <span class="event-action">
                  创建了日程
                </span>
                <span class="event-text">
                  <span class="emphasize">
                    <a href="/teams/124c/calendar_events/823f85599c074050a3c8b6e07a321a13" class="calendar_event-rest" data-stack="true">新的日程安排</a>
                  </span>
                </span>
              </div>
             <div class="event-body">
               <a href="/projects/48ca/todos/c9dd#c563" class="event-text" data-stack="true" title="干的好！">干的好！</a>
             </div>
          </div>
        </div>
      </div>

      <div class="events-ancestor" data-ancestor-guid="b40ee937044742cfb92aeb8e5590c9a1">
        <h5 class="events-ancestor-title">
          <a href="/teams/124c/calendars" target="_blank" title="法定假日">法定假日</a>
        </h5>
        <div class="event event-common event-calendarevent-add" id="event-87764702" data-ancestor-guid="b40ee937044742cfb92aeb8e5590c9a1" data-ancestor-name="法定假日" data-ancestor-url="/teams/124c/calendars">
         <a href="/members/4a" class="from" target="_blank"><img alt="淇淇" class="avatar" src="https://tower.im/assets/default_avatars/noon.jpg"></a>
         <i class="icon-event"></i>

         <div class="event-main">
           <div class="event-head">
             <a href="#event-87764702" data-created-at="2016-11-02T22:09:11+08:00" class="event-created-at">22:09</a>
             <span class="event-actor">
               <a href="/members/4a" class="link-member" target="_blank">淇淇</a>
             </span>
             <span class="event-action">
               创建了日程
             </span>
             <span class="event-text">
               <span class="emphasize">
                 <a href="/teams/124c/calendar_events/0317a81d0af84802ba3b5dd8db6f6bcd" class="calendar_event-rest" data-stack="true">新的日程安排</a>
               </span>
             </span>
           </div>
         </div>
        </div>
      </div>
    </div>
  </div>
  <div class="events-day" data-absdate="2016-11-02T00:00:00+08:00">
    <h4 class="events-day-title">昨</h4>
    <div class="events-day-content">
      <div class="events-ancestor" data-ancestor-guid="64fc76d9796d4f86920fdfe0660cd3cc">
        <h5 class="events-ancestor-title">
          <a href="/teams/124c/calendars" target="_blank" title="工作安排">工作安排</a>
        </h5>
        <div class="event event-common event-calendarevent-add" id="event-87764719" data-ancestor-guid="64fc76d9796d4f86920fdfe0660cd3cc" data-ancestor-name="工作安排" data-ancestor-url="/teams/124c/calendars">
          <a href="/members/4a" class="from" target="_blank">
            <img alt="淇淇" class="avatar" src="https://tower.im/assets/default_avatars/noon.jpg"></a>
            <i class="icon-event"></i>
            <div class="event-main">
              <div class="event-head">
                <a href="#event-87764719" data-created-at="2016-11-02T22:09:27+08:00" class="event-created-at">22:09</a>
                <span class="event-actor">
                  <a href="/members/4a" class="link-member" target="_blank">淇淇</a>
                </span>
                <span class="event-action">
                  创建了日程
                </span>
                <span class="event-text">
                  <span class="emphasize">
                    <a href="/teams/124c/calendar_events/823f85599c074050a3c8b6e07a321a13" class="calendar_event-rest" data-stack="true">新的日程安排</a>
                  </span>
                </span>
              </div>
             <div class="event-body">
               <a href="/projects/48ca/todos/c9dd#c563" class="event-text" data-stack="true" title="干的好！">干的好！</a>
             </div>
          </div>
        </div>
      </div>

      <div class="events-ancestor" data-ancestor-guid="b40ee937044742cfb92aeb8e5590c9a1">
        <h5 class="events-ancestor-title">
          <a href="/teams/124c/calendars" target="_blank" title="法定假日">法定假日</a>
        </h5>
        <div class="event event-common event-calendarevent-add" id="event-87764702" data-ancestor-guid="b40ee937044742cfb92aeb8e5590c9a1" data-ancestor-name="法定假日" data-ancestor-url="/teams/124c/calendars">
         <a href="/members/4a" class="from" target="_blank"><img alt="淇淇" class="avatar" src="https://tower.im/assets/default_avatars/noon.jpg"></a>
         <i class="icon-event"></i>

         <div class="event-main">
           <div class="event-head">
             <a href="#event-87764702" data-created-at="2016-11-02T22:09:11+08:00" class="event-created-at">22:09</a>
             <span class="event-actor">
               <a href="/members/4a" class="link-member" target="_blank">淇淇</a>
             </span>
             <span class="event-action">
               创建了日程
             </span>
             <span class="event-text">
               <span class="emphasize">
                 <a href="/teams/124c/calendar_events/0317a81d0af84802ba3b5dd8db6f6bcd" class="calendar_event-rest" data-stack="true">新的日程安排</a>
               </span>
             </span>
           </div>
         </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class='wrapper'>
  <%= render "header" %>

  <div class="container workspace simple-stack simple-stack-transition">
    <div class="page page-root simple-pjax">
      <div class="page-inner" id="page-events" data-page-name="动态" data-since="2016-11-03 02:54:27 UTC">
        <%= react_component 'Events', props: { events:   @events,
                                               projects: @projects,
                                               members:  @members
        } %>

      </div>
    </div>
  </div>
  <%= render "footer" %>
</div>

app/views/hello_world/index.html.erb
<h1 class="alert alert-info this-works">Hello World</h1>
<%= react_component("HelloWorldApp", props: @hello_world_props, prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tower</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="mac">
    <div style="width: 100%; margin: 0 auto;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(project, url: team_projects_path) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/index.html.erb
<h1>Projects#index</h1>
<p>Find me in app/views/projects/index.html.erb</p>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h1>Projects#show</h1>
<p>Find me in app/views/projects/show.html.erb</p>

app/views/todos/_form.html.erb
<%= form_for(todo, url: project_todos_path) do |f| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :due_date %>
    <%= f.datetime_select :due_date %>
  </div>

  <div class="field">
    <%= f.label :executor_id %>
    <%= f.number_field :executor_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Due date</th>
      <th>Executor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.title %></td>
        <td><%= todo.content %></td>
        <td><%= todo.due_date %></td>
        <td><%= todo.executor_id %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', project_todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @todo.content %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @todo.due_date %>
</p>

<p>
  <strong>Executor:</strong>
  <%= @todo.executor_id %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>